### ISSUE TITLE
Add an XS layout/breakpoint

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-grid#61]
At 600px it's still feasible to have plenty of UI elements which take up half the width (e.g., next article cards), whereas at 240px it becomes very impractical. I think o-grid should give developers a built in breakpoint at about 400px to be able to define a layout for very small screens.

@danskinner @kaelig

**Comment by kaelig** [comment]
Breakpoints are now:
```scss
$o-grid-layouts: (
	S:  _oGridWidth($column-width: 30px), // 490px
	M:  _oGridWidth($column-width: 50px), // 730px
	L:  _oGridWidth($column-width: 70px), // 970px
	XL: _oGridWidth($column-width: 90px)  // 1210px
) !default;
```

In a sense, XS is the default breakpoint (240-490px).

**Comment by wheresrhys** [comment]
Just been looking at this again. Can S kick in at the smaller value suggested initially of 370px? There is a big difference between devices of width 240px (which I think is still the minimum width grid will go to?) and 490px - to not offer a breakpoint inbetween leaves this issue barely addressed. @simonwilliamsFT @kaelig 

PS - sorry for raising this so late in the day, only just picked up on the breakpoint change

**Comment by kaelig** [comment]
@wheresrhys Thanks for looking at it. The range of things than can happen in between 240px and 490px is endless, and require some fine-tuning to be done well. The breakpoints are "global layout sizes", which doesn't exclude more a granular approach with tweakpoints in between two breakpoints.

For argument's sake, let's say there is an element that needs to be floated when the viewport reaches 337px wide. It would be possible to use Sass MQ `mq(337px)` or `oGridRespondTo(337px)` (or even a simple media query, but I'd recommend to stick with the mixins `mq` and `oGridRespondTo`).

```scss
.my-element {
  // default rules

  @include mq(337px) {
     // tweaks
    @include oGridColumn(1/2);
  }
}
```

Feel free to have a look at the "Final Thoughts" of this article: http://www.sitepoint.com/breakpoints-tweakpoints-sass/ where @hugogiraudel explains how to create component-specific and project-specific media query wrappers for Sass MQ.

**Comment by wheresrhys** [comment]
I agree that fine-tuning can, and should, be done on a product level, but I still think it would be more useful for the difference between breakpoints to be smaller between say XS and S compared to between L and XL.... a mildly logarithmic progression would be better I think.

At present the difference between each pair of adjacent breakpoints is roughly 240px, but this makes the implicit assumption that adding 240px to the width has a constant impact/utility regardless of what the original width was. It fails to acknowledge that adding 240px to 240px doubles the width, whereas adding 240px to 970px only adds 1/5th.

It's o-grid's job to standardise on useful default breakpoints and I don't think the S breakpoint is as useful as it could be. We may well end up hacking in a smaller breakpoint for use across next. See below - 2 cols would work at the second width but not at the first.

![image](https://cloud.githubusercontent.com/assets/447559/6248202/f10e2000-b774-11e4-8578-2d078ad757e0.png)
![image](https://cloud.githubusercontent.com/assets/447559/6248210/02ee67a8-b775-11e4-8bbf-b9c067d02d2b.png)

**Comment by kaelig** [comment]
I see what you mean, could it work for you to add a breakpoint, using variable `$o-grid-layouts`?

```scss
// Add the "Next Small" tweakpoint
$o-grid-layouts: map-merge((NS: 370px), $o-grid-layouts);
```

**Comment by AlbertoElias** [comment]
But why isn't the default S layout up to discussion?

**Comment by wheresrhys** [comment]
That would work for us yes - what a wonderfully flexible grid you've made! 

I still think the constant 240px interval between the default breakpoints isn't optimal for targeting handheld devices though. We could, I presume, overwrite all the breakpoints to whichever values we want?

**Comment by wheresrhys** [comment]
@AlbertoElias well said comrade :)

**Comment by kaelig** [comment]
I agree that between XS and S breakpoints, there is a *lot* of room for layout changes.

Here is a breakdown of my views on the new breakpoints and __why they exist__:

### XS (240px-489px)

We make sure the content is readable but let's be honest, it won't be very usable, which is probably fine for now, as watches with a browsers and really old phones aren't a concern.

#### Why no global breakpoints in between?
1. Too many possibilities: there's a lot of room for layout changes in that range, which I think are hard to sum up with a potential "370px" breakpoint, because precision is needed and products will still need to introduce other tweakpoints (maybe one component at 320px, and another component at 390px, these things need to be precisely set with designers).
2. Product decisions: depending on your audience and gathered data, a product can decide to micro-optimise with tweakpoints. The Origami team doesn't have this luxury (no data or user testing at the moment), so having a simplified "one mobile breakpoint to rule them all" should make development and design easier and less costly. __Feel free to debate this point, this is an opinion, not a fact.__

### S (490px-729px)

Probably the layout that should get the less love and focus because I assume this is the smaller part of our audience.

- Small screens, also called big phones :)
- It's an actual break from extra small screens
- Again, a lot of room for tweakpoints.

### M 730px-969px

- 768px is iPad portrait
- a range of tablet devices

### L 970px-1209px

Serves easily two big and very different parts of our audience:

- IE8 (in fixed layout, set at 970px)
- 1024px is iPad landscape

### XL 1210px

Most computer screens today, we might add another breakpoint after that one later, but for now it's already a pretty big scope for designers to think about.

====

Does that help? I think a lack of communication on my side led to a misunderstanding, and hopefully this breakdown helps conveying this message: __feel free to add tweakpoints__!

**Comment by kaelig** [comment]
As discussed last week, a product can add their own layouts and tweak the default breakpoints.

The Next FT is experimenting with a XS breakpoint, which might become part of the default set later on. Closing this, as it's no longer an issue.
